### ISSUE TITLE
recent chrome doesn't seem to be able to upload chrome trace

### ISSUE THREAD

**Issue by dustin** [ethercrow/opentelemetry-haskell#59]
I tried running megaexample and then using `eventlog-to-chrome read x.eventlog` I ended up with a file chrome wouldn't read.

Chrome gives the following error:

```
While importing:
Error: pid must be provided
    at new Process (chrome://tracing/tracing.js:3608:27)
    at Model.getOrCreateProcess (chrome://tracing/tracing.js:3659:126)
    at TraceEventImporter.processCounterEvent (chrome://tracing/tracing.js:6294:23)
    at TraceEventImporter.processEvent_ (chrome://tracing/tracing.js:6354:601)
    at TraceEventImporter.importEvents (chrome://tracing/tracing.js:6346:70)
    at chrome://tracing/tracing.js:2018:232
    at chrome://tracing/tracing.js:2014:268
    at Task.run (chrome://tracing/tracing.js:3278:95)
    at runAnother (chrome://tracing/tracing.js:3281:371)
    at runTask (chrome://tracing/tracing.js:3043:57)
```

Eventlog and translated JSON attached:

[eventlog.zip](https://github.com/ethercrow/opentelemetry-haskell/files/7358057/eventlog.zip)

**Comment by ethercrow** [comment]
Thank you for reporting! The `pid` field has been indeed missing from some fields in the chrome output.

https://github.com/ethercrow/opentelemetry-haskell/commit/d05256ae6eece4cc689b3de053b1b2d040f68c94 should fix it.

**Comment by pepeiborra** [comment]
@ethercrow could you upload a new Hackage package with this fix please? Thanks!
